version: "2.0.0-{build}"
skip_tags: true
clone_depth: 1
branches:
  only:
    - master
    - /rc\/([\d\w\-\.]+)/
    - config/ci
image:
  #  - Ubuntu2004
  - Visual Studio 2022
for:
  - matrix:
      only:
        - image: Ubuntu2004
    cache:
      - $HOME/.xmake/
    install:
      - sudo apt install g++ gcc
      - if [ ! -f "~/.xmake/profile" ]; then curl -fsSL https://xmake.io/shget.text | bash; fi
      - source ~/.xmake/profile
      - xmake --version
  - matrix:
      only:
        - image: Visual Studio 2022
    install:
      - ps: Invoke-Expression (Invoke-Webrequest 'https://xmake.io/psget.text' -UseBasicParsing).Content
      - ps: xmake --version
#    cache:
#      - "%userprofile%\\xmake"

build_script:
  - xmake b -v
#  - xmake i -o temp
