version: "2.0.0-{build}"
skip_tags: true
clone_depth: 1
branches:
  only:
    - master
    - /rc\/([\d\w\-\.]+)/
    - config/ci
image:
  - Ubuntu2004

cache:
  - ~/.xmake
install:
  - apt update g++ gcc
  - if [ ! -f "~/.xmake/profile" ]; then curl -fsSL https://xmake.io/shget.text | bash; fi
  - source ~/.xmake/profile
  - xmake --version

build_script:
  - xmake b -v
  - xmake i -o temp
